---
###
# Variables default values
##
# We recommend to use production values here
# These variables can be overridden later in other group_vars files
#
# Here is the Ansible groups structure:
#  all
#  ├── production
#  ├── staging
#  └── any_other_remote_environment...
#
# Each group has its "_overrides" counterpart, which enables you to override
#  some variables locally in a xxx_overrides.yml file, which is not versionned
# Have a look at .sample.yml files to see some examples
##

## Additional software that is going to be installed on all the nodes
## to facilitate your life managing them when you need to SSH them
additional_packages:
  - vim
  - htop


# Add the names of the users who will have root ssh access to all nodes,
# and then add a public key to pubkeys with the file named for each user
# eg. 
# users: 
#  - sergio

users:

# Domains
domains:
  main: "xapted.dev" # REPLACE THIS


# Enable traefik ACME feature
# If enabled, traefik will use Let's Encrypt to get an SSL certificate automatically
# Should be disabled only on local environments (localhost or vagrant)
letsencrypt: True
letsencrypt_email: admin@{{ domains.main }}


# geerlingguy.docker role configuration
docker_edition: ce


#### CORE

deploly_portainer: true