---
# We require docker to make this work
- name: Installing Docker
  become: yes
  import_role:
    name: geerlingguy.docker

- name: Install python docker
  become: true
  package:
    name:
      - python3-docker