---
- name: Initialize Digital Ocean volumes if configured
  when: digital_ocean_volumes is defined
  block:
    - name: Create mount point if does not exist
      ansible.builtin.file:
        path: "{{ item.mount_point }}"
        state: directory
        recurse: yes
      with_items: "{{ digital_ocean_volumes }}"
      when: digital_ocean_volumes is defined

    # TO DO - CHECK IF FILE SYSTEM NEEDS FORMATING
    # - name: Format volume
    #   mkfs:
    #     fstype: ext4
    #     state: formated
    #     dev: "/dev/disk/by-id/{{volume_id}}"
    #   with_items: "{{ digital_ocean_volumes }}"

    - name: Mount filesystem
      mount:
        fstype: ext4
        src: "/dev/disk/by-id/{{item.volume_id}}"
        path: "{{ item.mount_point }}"
        state: mounted
        opts: discard,defaults,nofail
        boot: true
      register: mount_info
      with_items: "{{ digital_ocean_volumes }}"
      when: digital_ocean_volumes is defined